name: testing linting and formatting PRs

on:
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Say Hello World
        run: echo "Hello world"

      - name: Build Docker container
        run: docker build -t my-app .

      - name: Run Lint
        run: docker run my-app npm run lint

      - name: Run Tests
        run: docker run my-app npm test