name: testing linting and formatting PRs

on:
  pull_request:
    branches:
      - main

jobs:
  format-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker container
        run: docker build -t my-app .

      - name: Run Lint check
        run: docker run --rm my-app npm run lint

      - name: Run Prettier
        run: docker run --rm my-app npm run format